@NMT_api_HostAddress = http://localhost:5114

GET {{NMT_api_HostAddress}}/
Accept: application/json

###

GET {{NMT_api_HostAddress}}/health
Accept: application/json

###

POST {{NMT_api_HostAddress}}/translate
Content-Type: application/json

{
  "text": "Bonjour tout le monde",
  "sourceLanguage": "fr",
  "targetLanguage": "en",
  "maxNewTokens": 512,
  "numBeams": 5
}

###
