@NMT_api_HostAddress = http://localhost:5114

POST {{NMT_api_HostAddress}}/api/auth/token
Accept: application/json

###

GET {{NMT_api_HostAddress}}/api/translations/languages
Accept: application/json

###

GET {{NMT_api_HostAddress}}/api/translations/onnx/model
Accept: application/json

###

POST {{NMT_api_HostAddress}}/api/translations/text
Content-Type: application/json

{
  "text": "Bonjour tout le monde",
  "sourceLanguage": "fr",
  "targetLanguage": "en",
  "maxNewTokens": 512
}

###
